// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/63b7a070257fd7638af9dee0
###
GET http://localhost:8080/contacts/63b7a2cb2c11b1efda73e47a
###
GET http://localhost:8080/contacts/63b7a2cb2c11b1efda73e47b
###
GET http://localhost:8080/contacts/63b7a2cb2c11b1efda73e47c

// PRODUCTION Deploy
###
GET https://cse341-instructor.herokuapp.com/contacts
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b2
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b3
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b4